version: '3'
services:
  web:
    image: alanlab/app_loja:v2

    ports:
      - "80:3000"
    depends_on:
      - database
    environment:
      RAILS_ENV: production
    volumes:
      - storage:/media
  db-migration:
    image: alanlab/app_loja:v2
    command: ["./wait-for", "--timeout=300", "database:5432", "--", "bin/rails", "db:create", "db:migrate"]
    environment:
      RAILS_ENV: production
    depends_on:
      - database  
    deploy:
      restart_policy:
        condition: none
  database:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      RAILS_ENV: production
volumes:
  db_data:
  storage:  

