version: '3'
services:
  web:
    image: alanlab/cluster_app:banco_v4
    ports:
      - "80:3000"
    environment:
      DATABASE_HOST: database 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alan123
      POSTGRES_DB: teste_db
  db-migration:
    image: alanlab/cluster_app:banco_v4
    command: ["bin/rails", "db:migrate", "RAILS_ENV=", "production"]
    environment:
      DATABASE_HOST: database 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alan123
      POSTGRES_DB: teste_db
    deploy:
      restart_policy:
        condition: none
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alan123
      POSTGRES_DB: teste_db
