version: '3'
services:
  web:
    image: alanlab/cluster_app:banco_v3
    command: ["./wait-for", "--timeout=300", "database:5432", "--","bin/rails", "db:migrate", "-e", "production"]
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: database 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alan123
      POSTGRES_DB: teste_db
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alan123
      POSTGRES_DB: teste_db
