version: '3'
services:
  web:
    image: alanlab/cluster_app:banco_v5
    ports:
      - "80:3000"
    environment:
      DATABASE_HOST: database 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alan123
      POSTGRES_DB: teste_db
  db-migration:
    image: alanlab/cluster_app:banco_v5
    command: ["./wait-for", "--timeout=300", "database:5432", "--", bin/rails", "db:migrate"]
    environment:
      DATABASE_HOST: database 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alan123
      POSTGRES_DB: teste_db
    deploy:
      restart_policy:
        condition: none
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alan123
      POSTGRES_DB: teste_db
